sudo: required
services:
    - docker
before_install:
    - docker build -t erdoganabaci/docker-react -f Dockerfile.dev .
script:
    - docker run -it -e CI=true erdoganabaci/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-378231579342"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY